name: Test Python implementation

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: pip3 install bitstring cryptography
    - name: Check KATs
      run: |
        cd python3
        python3 nist_kat.py
